ALTER TABLE "Product" ADD CONSTRAINT "product_nonnegative" CHECK (price >= 0 AND stock >= 0 AND units > 0);
ALTER TABLE "Box" ADD CONSTRAINT "box_valid" CHECK (price >= 0 AND capacity > 0);
ALTER TABLE "Packaging" ADD CONSTRAINT "packaging_valid" CHECK (price >= 0 AND kind IN ('ribbon','tissue','extra'));
ALTER TABLE "Order" ADD CONSTRAINT "order_total_valid" CHECK (total >= 0 AND "deliveryFee" >= 0);
ALTER TABLE "Order" ADD CONSTRAINT "order_status_valid" CHECK (status IN ('NEW','CONFIRMED','PREPARING','READY','OUT_FOR_DELIVERY','DELIVERED','CANCELLED'));
ALTER TABLE "Order" ADD CONSTRAINT "payment_status_valid" CHECK ("paymentStatus" IN ('UNPAID','PAID'));
ALTER TABLE "DeliverySlot" ADD CONSTRAINT "slot_capacity_valid" CHECK (capacity >= 0 AND reserved >= 0 AND reserved <= capacity);
ALTER TABLE "OrderItem" ADD CONSTRAINT "order_item_valid" CHECK (quantity > 0 AND total >= 0);
ALTER TABLE "Reservation" ADD CONSTRAINT "reservation_valid" CHECK (quantity > 0);
ALTER TABLE "GiftComponent" ADD CONSTRAINT "component_valid" CHECK (quantity > 0);
ALTER TABLE "DeliveryZone" ADD CONSTRAINT "zone_fee_valid" CHECK (fee >= 0);
ALTER TABLE "Payment" ADD CONSTRAINT "payment_amount_valid" CHECK (amount >= 0);
ALTER TABLE "User" ADD CONSTRAINT "role_valid" CHECK (role IN ('OWNER','STAFF'));
ALTER TABLE "Gift" ADD CONSTRAINT "gift_box_fk" FOREIGN KEY ("boxId") REFERENCES "Box"(id);
CREATE INDEX "Session_userId_idx" ON "Session"("userId");
CREATE INDEX "Account_userId_idx" ON "Account"("userId");
CREATE INDEX "OrderHistory_orderId_idx" ON "OrderHistory"("orderId");
CREATE INDEX "OrderItem_orderId_idx" ON "OrderItem"("orderId");
CREATE INDEX "Payment_orderId_idx" ON "Payment"("orderId");
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");
CREATE INDEX "Inquiry_createdAt_idx" ON "Inquiry"("createdAt");
